= Priority Support
// URIs
:uri-website: https://mantoso.com/priority-support

This is an open source project. The amount of time we have available to help resolve issue's is often limited as all help outside of our own priorities is provided on a volunteer basis. If you want priority help, get up to speed quickly, require training,  mentoring, or need full 24 x 7 production support, contact us.

Mantoso offers priority support for all of our open source projects where you will work directly with our team of experts via email, a private Slack channel or video conferencing.

We deliver value at a fraction of the cost of a full time Engineer, Developer or Cloud Architect.

Services we provide:

- Architecture
- Release Engineering
- Security Baseline
- Questions
- Troubleshooting
- Code Reviews
- Priority bug fixes

{uri-website}[Contact us] to learn more about priority support.

== Why not Github

GitHub is our office, it's the place where our development team does its work. We use the issue list to keep track of bugs and the features that we are working on. We do this openly for transparency.

Please keep in mind that our repositories are FLOSS, and free support is provided by the goodwill of our wonderful community members.
